apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: prometheus-monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.21.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-storage
              mountPath: /etc/prometheus/
            - name: prometheus-persistent-storage
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-storage
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-persistent-storage
          emptyDir: {}
