apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      name: grafana-server
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.2.1
        ports:
        - name: grafana
          containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          limits:
            cpu: "1000m"
            memory: "500Mi"
          requests: 
            cpu: "500m"
            memory: "250Mi"
        volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
          - name: grafana-storage-volume
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-grafana
