apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-server
  name: grafana-server
  namespace: prometheus-monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana-server
