apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-resource-quota
  labels:
    name: monitoring-resource-quota
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---

apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limit-range
  labels:
    name: monitoring-limit-range
spec:
  limits:
  - type: Pod
    max:
      cpu: "1000m"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 10Mi
  - type: Container
    default:
      cpu: 500m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 50Mi
    max:
      cpu: "1000m"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 10Mi
