apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard  
  nfs:
    path: /home/NFS/Prometheus
    server: 192.168.0.203

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-grafana
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard  
  nfs:
    path: /home/NFS/Grafana
    server: 192.168.0.203
